"""update quote

Revision ID: ea8cd92c0c00
Revises: 9d6b668c9f47
Create Date: 2022-02-15 21:45:52.381960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea8cd92c0c00'
down_revision = '9d6b668c9f47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('quote', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotes', 'quote')
    # ### end Alembic commands ###
